version: "3.4"

services:
  sports_api:
    build:
      context: .
      target: prod
    image: josephsiefers/sports_api:prod
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - RAILS_ENV=production

  sports_api_dev:
    build:
      context: .
      target: dev
    image: josephsiefers/sports_api:dev
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    volumes:
      - .:/home/app

  db:
    image: mysql:5.7
    container_name: sports_api_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
